# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EHWRlr6Nb60NW5PrGPBFwoTF0d5bsKCO

Q1. Load the "titanic" dataset using the load_dataset function of seaborn. Use Plotly express to plot a
scatter plot for age and fare columns in the titanic dataset.
"""

import seaborn as sns
import plotly.express as px
titanic= sns.load_dataset("titanic")
titanic
fig = px.scatter(titanic, x= "age" , y = "fare")
fig.show()

"""Q2. Using the tips dataset in the Plotly library, plot a box plot using Plotly express."""

import seaborn as sns
import plotly.express as px
tips = sns.load_dataset("tips")
tips
px.box(tips, x="total_bill",y="tip")

"""Q3. Using the tips dataset in the Plotly library, Plot a histogram for x= "sex" and y="total_bill" column in
the tips dataset. Also, use the "smoker" column with the pattern_shape parameter and the "day"
column with the color parameter.
"""

import seaborn as sns
import plotly.express as px
tips = sns.load_dataset("tips")
fig = px.histogram(tips, x = 'sex', y ='total_bill',color = 'day',pattern_shape='smoker')
fig.show()

"""Q4. Using the iris dataset in the Plotly library, Plot a scatter matrix plot, using the "species" column for
the color parameter.
Note: Use "sepal_length", "sepal_width", "petal_length", "petal_width" columns only with the
dimensions parameter.
"""

import plotly.express as px
iris = px.data.iris()
fig = px.scatter_matrix(iris, dimensions = ["sepal_length","sepal_width","petal_length","petal_width"], color = "species")
fig.show()

"""Q5. What is Distplot? Using Plotly express, plot a distplot.

Ans:
A distplot is a statistical plot that shows the distribution of a dataset. It is a combination of a histogram, a kernel density estimate (KDE), and a rug plot. The histogram shows the frequency of each value in the dataset, the KDE shows the smooth distribution of the data, and the rug plot shows the individual values in the dataset.
"""

import plotly.express as px
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset("tips")
sns.displot(df["total_bill"])
plt.show()

